image: cznic/ubuntu:16.04-knot-resolver

stages:
  - configure
  - build
  - test
  - deploy

variables:
  DEBIAN_FRONTEND: noninteractive
  LC_ALL: C.UTF-8
  GIT_SUBMODULE_STRATEGY: recursive

configure:linux:amd64:
  stage: configure
  script:
    - meson -Dprefix=$(pwd)/.local build
  artifacts:
    untracked: true
  tags:
    - docker
    - linux
    - amd64
  
build:linux:amd64:
  stage: build
  dependencies:
    - configure:linux:amd64
  script:
    - ninja -C build
    - ninja -C build install
  artifacts:
    untracked: true
  tags:
    - docker
    - linux
    - amd64

test:linux:amd64:
  stage: test
  script:
    - ninja -C build test
  dependencies:
    - build:linux:amd64
  tags:
    - docker
    - linux
    - amd64

deckard:linux:amd64:
  stage: test
  script:
    - ninja -C build check-integration
  dependencies:
    - build:linux:amd64
  tags:
    - docker
    - linux
    - amd64

respdiff:linux:amd64:
  image: cznic/ubuntu-respdif:16.04
  stage: test
  script:
    - LD_LIBRARY_PATH=$(pwd)/.local/lib /home/kresdbench/run.sh $(pwd)/.local/sbin/kresd
    - /home/kresdbench/resolver-benchmarking/response_differences/nightly.sh
    - cp -r /home/kresdbench/resolver-benchmarking/response_differences/results $(pwd)
  artifacts:
    when: always
    expire_in: '1 week'
    paths:
      - results/*.json
      - results/*.out
      - results/*.log
  tags:
    - docker
    - linux
    - amd64
  allow_failure: true

#arm_build:
#  image: cznic/armhf-ubuntu:16.04
#  stage: build
#  script:
#    - make -k all
#  tags:
#    - docker
#    - linux
#    - arm

#arm_test:
#  image: armv7/armhf-ubuntu:16.04
#  stage: test
#  script:
#    - make -k check
#  tags:
#    - docker
#    - linux
#    - arm
